import { Lexend_Deca } from 'next/font/google'

const LexendDeca = Lexend_Deca({ subsets: ['latin'] })

export const metadata = {
  title: 'Proxy-demo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={LexendDeca.className}>{children}</body>
    </html>
  )
}
